<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Soundora.Application\Soundora.Application.csproj" />
    <ProjectReference Include="..\..\Core\Soundora.Domain\Soundora.Domain.csproj" />
  </ItemGroup>

</Project>
